### PR TITLE
Added and fixed links in this menu and footer

### PR DESCRIPTION
**Pull request by Swayamsvk**

### CODE REVIEW

**Comment by Swayamsvk** [comment]
Added links for twitter and instagram, in this menu.
Updated link for twitter in footer and add instagram icon in footer.

**Comment by stuntguy3000** [comment]
You've made a mistake, you've comitted node_modules.

**Comment by ankitjena** [comment]
@Swayamsvk Do not include node_modules in your commit. Kindly recommit.

**Review by ankitjena — CHANGES_REQUESTED** [review]
@Swayamsvk Do not include `node_modules` in your commit. Kindly recommit.

**Comment by stuntguy3000** [comment]
@ankitjena I see node_modules is apart of the repo, should that be scrapped with a gitignore?

**Comment by ankitjena** [comment]
@stuntguy3000 Yes, that totally skipped my eye. I'm creating a issue for it.

**Comment by ankitjena** [comment]
@Swayamsvk the issue for footer has been fixed in #45

**Pull request closed without merging**
